[tool.black]
line-length = 79
exclude = '''
/(
    venv
)/
'''

[tool.autoflake]
remove-unused-variables = true
remove-all-unused-imports = true
exclude = '''
venv
'''

[tool.commitizen]
name = "cz_gitmoji"